name: TentThis
main: ssell.TentThis.TentThis
version: "2.1.0"
author: ssell
commands:
    ttTent:
        description: Sets the plugin to start waiting to build.
        usage: /<command> 
    ttSchema:
        description: Set the tent schema to be built.
        usage: /<command> 
    ttInfo:
        description: Reports the current schema.
        usage: /<command>
    ttNoCommand:
        description: Enables/Disables the need to enter /ttTent to build.
        usage: /<command>
    ttReload:
        description: Finds new CreationBlock without having to restart server.
        usage: /<command>
    ttLimit:
        description: Sets the tent limit for provided player or everyone.
        usage: /<command>
    ttReverseSchema:
        description: Sets the tent limit for provided player or everyone.
        usage: /<command>